#!/bin/sh

# Module showing network traffic. Shows how much data has been received (RX) or
# transmitted (TX) since the previous time this script ran. So if run every
# second, gives network traffic per second.
#
# Color code with \x0b, \x0c, \x0d, ... etc being the indeces of the colors
# array from within the config.h of dwm
# static const char *colors[][3]      = {
# 	/*               fg         bg         border   */
# 	[SchemeNorm] = { normfgcolor, normbgcolor, normbordercolor },
# 	[SchemeCol1] = { warnfgcolor, normbgcolor, normbordercolor },
# 	[SchemeCol2] = { critfgcolor, normbgcolor, normbordercolor },
# 	[SchemeCol3] = { selbordercolor, normbgcolor, normbordercolor },
# 	[SchemeSel]  = { selfgcolor,  selbgcolor,  selbordercolor  },
# };



case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e bmon ;;
	3) notify-send "🌐 Network traffic module" "🔻: Traffic received
🔺: Traffic transmitted" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=${XDG_CACHE_HOME:-$HOME/.cache}/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

printf "﮾%4sB ﯁%4sB\\n" $(numfmt --to=iec $rx) $(numfmt --to=iec $tx)
